title = "Baltzakis Themis"
baseURL = "https://laskaridissa.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Thermopilon 15 Koropi, GR"
email = "baltzakis.themis@gmail.com"
favicon = "/favicon.ico"
firstName = "Themistoklis"
lastName = "Baltzakis"
phone = "+30 6977777838"
profileImage = "img/TechChat.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
#trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/baltzakis-themis/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/Themis128/"
name = "GitHub"

#[[params.handles]]
#link = "https://bitbucket.org/eddiewebb/"
#name = "Bitbucket"

#[[params.handles]]
#link = "https://stackoverflow.com/users/story/82880"
#name = "Stack Overflow"

#[[params.handles]]
#link = "https://keybase.io/edwardawebb"
#name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"